# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vagrant/projects/jukebox-core/src/jukeboxcore/gui/widgets/guerillamgmt.ui'
#
# Created: Fri May 29 16:28:10 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_guerillamgmt_mwin(object):
    def setupUi(self, guerillamgmt_mwin):
        guerillamgmt_mwin.setObjectName("guerillamgmt_mwin")
        guerillamgmt_mwin.resize(1379, 1024)
        self.central_widget = QtGui.QWidget(guerillamgmt_mwin)
        self.central_widget.setObjectName("central_widget")
        self.central_vbox = QtGui.QVBoxLayout(self.central_widget)
        self.central_vbox.setObjectName("central_vbox")
        self.pages_tabw = QtGui.QTabWidget(self.central_widget)
        self.pages_tabw.setObjectName("pages_tabw")
        self.prjs_widget = QtGui.QWidget()
        self.prjs_widget.setObjectName("prjs_widget")
        self.prjs_vbox = QtGui.QVBoxLayout(self.prjs_widget)
        self.prjs_vbox.setObjectName("prjs_vbox")
        self.prjs_tablev = QtGui.QTableView(self.prjs_widget)
        self.prjs_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.prjs_tablev.setObjectName("prjs_tablev")
        self.prjs_tablev.horizontalHeader().setStretchLastSection(True)
        self.prjs_vbox.addWidget(self.prjs_tablev)
        self.prjs_btns_vbox = QtGui.QHBoxLayout()
        self.prjs_btns_vbox.setObjectName("prjs_btns_vbox")
        self.prjs_prj_view_pb = QtGui.QPushButton(self.prjs_widget)
        self.prjs_prj_view_pb.setObjectName("prjs_prj_view_pb")
        self.prjs_btns_vbox.addWidget(self.prjs_prj_view_pb)
        self.prjs_prj_create_pb = QtGui.QPushButton(self.prjs_widget)
        self.prjs_prj_create_pb.setObjectName("prjs_prj_create_pb")
        self.prjs_btns_vbox.addWidget(self.prjs_prj_create_pb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.prjs_btns_vbox.addItem(spacerItem)
        self.prjs_vbox.addLayout(self.prjs_btns_vbox)
        self.pages_tabw.addTab(self.prjs_widget, "")
        self.prj_widget = QtGui.QWidget()
        self.prj_widget.setObjectName("prj_widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.prj_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.prj_sa = QtGui.QScrollArea(self.prj_widget)
        self.prj_sa.setWidgetResizable(True)
        self.prj_sa.setObjectName("prj_sa")
        self.prj_sa_widget = QtGui.QWidget()
        self.prj_sa_widget.setGeometry(QtCore.QRect(0, 0, 1321, 1628))
        self.prj_sa_widget.setObjectName("prj_sa_widget")
        self.gridLayout = QtGui.QGridLayout(self.prj_sa_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.prj_users_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_users_lb.sizePolicy().hasHeightForWidth())
        self.prj_users_lb.setSizePolicy(sizePolicy)
        self.prj_users_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.prj_users_lb.setObjectName("prj_users_lb")
        self.gridLayout.addWidget(self.prj_users_lb, 17, 0, 1, 1)
        self.prj_fps_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_fps_lb.sizePolicy().hasHeightForWidth())
        self.prj_fps_lb.setSizePolicy(sizePolicy)
        self.prj_fps_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prj_fps_lb.setObjectName("prj_fps_lb")
        self.gridLayout.addWidget(self.prj_fps_lb, 7, 0, 1, 1)
        self.prj_res_hbox = QtGui.QHBoxLayout()
        self.prj_res_hbox.setObjectName("prj_res_hbox")
        self.prj_res_x_sb = QtGui.QSpinBox(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_res_x_sb.sizePolicy().hasHeightForWidth())
        self.prj_res_x_sb.setSizePolicy(sizePolicy)
        self.prj_res_x_sb.setMaximum(9999)
        self.prj_res_x_sb.setProperty("value", 1920)
        self.prj_res_x_sb.setObjectName("prj_res_x_sb")
        self.prj_res_hbox.addWidget(self.prj_res_x_sb)
        self.prj_res_y_sb = QtGui.QSpinBox(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_res_y_sb.sizePolicy().hasHeightForWidth())
        self.prj_res_y_sb.setSizePolicy(sizePolicy)
        self.prj_res_y_sb.setMaximum(9999)
        self.prj_res_y_sb.setProperty("value", 1080)
        self.prj_res_y_sb.setObjectName("prj_res_y_sb")
        self.prj_res_hbox.addWidget(self.prj_res_y_sb)
        self.gridLayout.addLayout(self.prj_res_hbox, 8, 1, 1, 1)
        self.prj_atype_btns_hbox = QtGui.QHBoxLayout()
        self.prj_atype_btns_hbox.setObjectName("prj_atype_btns_hbox")
        self.prj_atype_view_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_atype_view_pb.setObjectName("prj_atype_view_pb")
        self.prj_atype_btns_hbox.addWidget(self.prj_atype_view_pb)
        self.prj_atype_add_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_atype_add_pb.setObjectName("prj_atype_add_pb")
        self.prj_atype_btns_hbox.addWidget(self.prj_atype_add_pb)
        self.prj_atype_create_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_atype_create_pb.setObjectName("prj_atype_create_pb")
        self.prj_atype_btns_hbox.addWidget(self.prj_atype_create_pb)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.prj_atype_btns_hbox.addItem(spacerItem1)
        self.gridLayout.addLayout(self.prj_atype_btns_hbox, 14, 1, 1, 1)
        self.prj_short_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_short_lb.sizePolicy().hasHeightForWidth())
        self.prj_short_lb.setSizePolicy(sizePolicy)
        self.prj_short_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prj_short_lb.setObjectName("prj_short_lb")
        self.gridLayout.addWidget(self.prj_short_lb, 1, 0, 1, 1)
        self.prj_fps_dsb = QtGui.QDoubleSpinBox(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_fps_dsb.sizePolicy().hasHeightForWidth())
        self.prj_fps_dsb.setSizePolicy(sizePolicy)
        self.prj_fps_dsb.setMaximum(999.0)
        self.prj_fps_dsb.setProperty("value", 25.0)
        self.prj_fps_dsb.setObjectName("prj_fps_dsb")
        self.gridLayout.addWidget(self.prj_fps_dsb, 7, 1, 1, 1)
        self.prj_desc_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_desc_lb.sizePolicy().hasHeightForWidth())
        self.prj_desc_lb.setSizePolicy(sizePolicy)
        self.prj_desc_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.prj_desc_lb.setObjectName("prj_desc_lb")
        self.gridLayout.addWidget(self.prj_desc_lb, 4, 0, 1, 1)
        self.prj_scale_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_scale_lb.sizePolicy().hasHeightForWidth())
        self.prj_scale_lb.setSizePolicy(sizePolicy)
        self.prj_scale_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prj_scale_lb.setObjectName("prj_scale_lb")
        self.gridLayout.addWidget(self.prj_scale_lb, 10, 0, 1, 1)
        self.prj_res_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_res_lb.sizePolicy().hasHeightForWidth())
        self.prj_res_lb.setSizePolicy(sizePolicy)
        self.prj_res_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prj_res_lb.setObjectName("prj_res_lb")
        self.gridLayout.addWidget(self.prj_res_lb, 8, 0, 1, 1)
        self.prj_semester_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_semester_lb.sizePolicy().hasHeightForWidth())
        self.prj_semester_lb.setSizePolicy(sizePolicy)
        self.prj_semester_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prj_semester_lb.setObjectName("prj_semester_lb")
        self.gridLayout.addWidget(self.prj_semester_lb, 6, 0, 1, 1)
        self.prj_created_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_created_lb.sizePolicy().hasHeightForWidth())
        self.prj_created_lb.setSizePolicy(sizePolicy)
        self.prj_created_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prj_created_lb.setObjectName("prj_created_lb")
        self.gridLayout.addWidget(self.prj_created_lb, 5, 0, 1, 1)
        self.prj_seq_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_seq_lb.sizePolicy().hasHeightForWidth())
        self.prj_seq_lb.setSizePolicy(sizePolicy)
        self.prj_seq_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.prj_seq_lb.setObjectName("prj_seq_lb")
        self.gridLayout.addWidget(self.prj_seq_lb, 11, 0, 1, 1)
        self.prj_name_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_name_lb.sizePolicy().hasHeightForWidth())
        self.prj_name_lb.setSizePolicy(sizePolicy)
        self.prj_name_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prj_name_lb.setObjectName("prj_name_lb")
        self.gridLayout.addWidget(self.prj_name_lb, 0, 0, 1, 1)
        self.prj_scale_cb = QtGui.QComboBox(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_scale_cb.sizePolicy().hasHeightForWidth())
        self.prj_scale_cb.setSizePolicy(sizePolicy)
        self.prj_scale_cb.setObjectName("prj_scale_cb")
        self.prj_scale_cb.addItem("")
        self.prj_scale_cb.addItem("")
        self.prj_scale_cb.addItem("")
        self.prj_scale_cb.addItem("")
        self.prj_scale_cb.addItem("")
        self.prj_scale_cb.addItem("")
        self.prj_scale_cb.addItem("")
        self.prj_scale_cb.addItem("")
        self.gridLayout.addWidget(self.prj_scale_cb, 10, 1, 1, 1)
        self.prj_created_dte = QtGui.QDateTimeEdit(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_created_dte.sizePolicy().hasHeightForWidth())
        self.prj_created_dte.setSizePolicy(sizePolicy)
        self.prj_created_dte.setReadOnly(True)
        self.prj_created_dte.setObjectName("prj_created_dte")
        self.gridLayout.addWidget(self.prj_created_dte, 5, 1, 1, 1)
        self.prj_short_le = QtGui.QLineEdit(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_short_le.sizePolicy().hasHeightForWidth())
        self.prj_short_le.setSizePolicy(sizePolicy)
        self.prj_short_le.setReadOnly(True)
        self.prj_short_le.setObjectName("prj_short_le")
        self.gridLayout.addWidget(self.prj_short_le, 1, 1, 1, 1)
        self.prj_dep_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_dep_lb.sizePolicy().hasHeightForWidth())
        self.prj_dep_lb.setSizePolicy(sizePolicy)
        self.prj_dep_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.prj_dep_lb.setObjectName("prj_dep_lb")
        self.gridLayout.addWidget(self.prj_dep_lb, 15, 0, 1, 1)
        self.prj_seq_tablev = QtGui.QTableView(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.prj_seq_tablev.sizePolicy().hasHeightForWidth())
        self.prj_seq_tablev.setSizePolicy(sizePolicy)
        self.prj_seq_tablev.setMinimumSize(QtCore.QSize(0, 300))
        self.prj_seq_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.prj_seq_tablev.setObjectName("prj_seq_tablev")
        self.prj_seq_tablev.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.prj_seq_tablev, 11, 1, 1, 1)
        self.prj_atype_tablev = QtGui.QTableView(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.prj_atype_tablev.sizePolicy().hasHeightForWidth())
        self.prj_atype_tablev.setSizePolicy(sizePolicy)
        self.prj_atype_tablev.setMinimumSize(QtCore.QSize(0, 250))
        self.prj_atype_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.prj_atype_tablev.setObjectName("prj_atype_tablev")
        self.prj_atype_tablev.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.prj_atype_tablev, 13, 1, 1, 1)
        self.prj_semester_le = QtGui.QLineEdit(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_semester_le.sizePolicy().hasHeightForWidth())
        self.prj_semester_le.setSizePolicy(sizePolicy)
        self.prj_semester_le.setObjectName("prj_semester_le")
        self.gridLayout.addWidget(self.prj_semester_le, 6, 1, 1, 1)
        self.prj_atype_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_atype_lb.sizePolicy().hasHeightForWidth())
        self.prj_atype_lb.setSizePolicy(sizePolicy)
        self.prj_atype_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.prj_atype_lb.setObjectName("prj_atype_lb")
        self.gridLayout.addWidget(self.prj_atype_lb, 13, 0, 1, 1)
        self.prj_dep_tablev = QtGui.QTableView(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.prj_dep_tablev.sizePolicy().hasHeightForWidth())
        self.prj_dep_tablev.setSizePolicy(sizePolicy)
        self.prj_dep_tablev.setMinimumSize(QtCore.QSize(0, 250))
        self.prj_dep_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.prj_dep_tablev.setObjectName("prj_dep_tablev")
        self.prj_dep_tablev.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.prj_dep_tablev, 15, 1, 1, 1)
        self.prj_user_tablev = QtGui.QTableView(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.prj_user_tablev.sizePolicy().hasHeightForWidth())
        self.prj_user_tablev.setSizePolicy(sizePolicy)
        self.prj_user_tablev.setMinimumSize(QtCore.QSize(0, 300))
        self.prj_user_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.prj_user_tablev.setObjectName("prj_user_tablev")
        self.prj_user_tablev.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.prj_user_tablev, 17, 1, 1, 1)
        self.prj_name_le = QtGui.QLineEdit(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_name_le.sizePolicy().hasHeightForWidth())
        self.prj_name_le.setSizePolicy(sizePolicy)
        self.prj_name_le.setReadOnly(True)
        self.prj_name_le.setObjectName("prj_name_le")
        self.gridLayout.addWidget(self.prj_name_le, 0, 1, 1, 1)
        self.prj_desc_pte = QtGui.QPlainTextEdit(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_desc_pte.sizePolicy().hasHeightForWidth())
        self.prj_desc_pte.setSizePolicy(sizePolicy)
        self.prj_desc_pte.setObjectName("prj_desc_pte")
        self.gridLayout.addWidget(self.prj_desc_pte, 4, 1, 1, 1)
        self.prj_seq_btns_hbox = QtGui.QHBoxLayout()
        self.prj_seq_btns_hbox.setObjectName("prj_seq_btns_hbox")
        self.prj_seq_view_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_seq_view_pb.setObjectName("prj_seq_view_pb")
        self.prj_seq_btns_hbox.addWidget(self.prj_seq_view_pb)
        self.prj_seq_create_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_seq_create_pb.setObjectName("prj_seq_create_pb")
        self.prj_seq_btns_hbox.addWidget(self.prj_seq_create_pb)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.prj_seq_btns_hbox.addItem(spacerItem2)
        self.gridLayout.addLayout(self.prj_seq_btns_hbox, 12, 1, 1, 1)
        self.prj_dep_btns_hbox = QtGui.QHBoxLayout()
        self.prj_dep_btns_hbox.setObjectName("prj_dep_btns_hbox")
        self.prj_dep_view_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_dep_view_pb.setObjectName("prj_dep_view_pb")
        self.prj_dep_btns_hbox.addWidget(self.prj_dep_view_pb)
        self.prj_dep_add_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_dep_add_pb.setObjectName("prj_dep_add_pb")
        self.prj_dep_btns_hbox.addWidget(self.prj_dep_add_pb)
        self.prj_dep_create_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_dep_create_pb.setObjectName("prj_dep_create_pb")
        self.prj_dep_btns_hbox.addWidget(self.prj_dep_create_pb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.prj_dep_btns_hbox.addItem(spacerItem3)
        self.gridLayout.addLayout(self.prj_dep_btns_hbox, 16, 1, 1, 1)
        self.prj_user_btns_hbox = QtGui.QHBoxLayout()
        self.prj_user_btns_hbox.setObjectName("prj_user_btns_hbox")
        self.prj_user_view_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_user_view_pb.setObjectName("prj_user_view_pb")
        self.prj_user_btns_hbox.addWidget(self.prj_user_view_pb)
        self.prj_user_add_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_user_add_pb.setObjectName("prj_user_add_pb")
        self.prj_user_btns_hbox.addWidget(self.prj_user_add_pb)
        self.prj_user_remove_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_user_remove_pb.setObjectName("prj_user_remove_pb")
        self.prj_user_btns_hbox.addWidget(self.prj_user_remove_pb)
        self.prj_user_create_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_user_create_pb.setObjectName("prj_user_create_pb")
        self.prj_user_btns_hbox.addWidget(self.prj_user_create_pb)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.prj_user_btns_hbox.addItem(spacerItem4)
        self.gridLayout.addLayout(self.prj_user_btns_hbox, 18, 1, 1, 1)
        self.prj_path_hbox = QtGui.QHBoxLayout()
        self.prj_path_hbox.setObjectName("prj_path_hbox")
        self.prj_path_le = QtGui.QLineEdit(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.prj_path_le.sizePolicy().hasHeightForWidth())
        self.prj_path_le.setSizePolicy(sizePolicy)
        self.prj_path_le.setReadOnly(True)
        self.prj_path_le.setObjectName("prj_path_le")
        self.prj_path_hbox.addWidget(self.prj_path_le)
        self.prj_path_view_pb = QtGui.QPushButton(self.prj_sa_widget)
        self.prj_path_view_pb.setObjectName("prj_path_view_pb")
        self.prj_path_hbox.addWidget(self.prj_path_view_pb)
        self.gridLayout.addLayout(self.prj_path_hbox, 2, 1, 1, 1)
        self.prj_path_lb = QtGui.QLabel(self.prj_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prj_path_lb.sizePolicy().hasHeightForWidth())
        self.prj_path_lb.setSizePolicy(sizePolicy)
        self.prj_path_lb.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prj_path_lb.setObjectName("prj_path_lb")
        self.gridLayout.addWidget(self.prj_path_lb, 2, 0, 1, 1)
        self.prj_sa.setWidget(self.prj_sa_widget)
        self.verticalLayout_2.addWidget(self.prj_sa)
        self.pages_tabw.addTab(self.prj_widget, "")
        self.seq_widget = QtGui.QWidget()
        self.seq_widget.setObjectName("seq_widget")
        self.seq_vbox = QtGui.QVBoxLayout(self.seq_widget)
        self.seq_vbox.setObjectName("seq_vbox")
        self.seq_sa = QtGui.QScrollArea(self.seq_widget)
        self.seq_sa.setWidgetResizable(True)
        self.seq_sa.setObjectName("seq_sa")
        self.seq_sa_widget = QtGui.QWidget()
        self.seq_sa_widget.setGeometry(QtCore.QRect(0, 0, 1337, 931))
        self.seq_sa_widget.setObjectName("seq_sa_widget")
        self.seq_grid = QtGui.QGridLayout(self.seq_sa_widget)
        self.seq_grid.setObjectName("seq_grid")
        self.seq_name_le = QtGui.QLineEdit(self.seq_sa_widget)
        self.seq_name_le.setReadOnly(True)
        self.seq_name_le.setObjectName("seq_name_le")
        self.seq_grid.addWidget(self.seq_name_le, 0, 1, 1, 1)
        self.seq_desc_lb = QtGui.QLabel(self.seq_sa_widget)
        self.seq_desc_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.seq_desc_lb.setObjectName("seq_desc_lb")
        self.seq_grid.addWidget(self.seq_desc_lb, 3, 0, 1, 1)
        self.seq_name_lb = QtGui.QLabel(self.seq_sa_widget)
        self.seq_name_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.seq_name_lb.setObjectName("seq_name_lb")
        self.seq_grid.addWidget(self.seq_name_lb, 0, 0, 1, 1)
        self.seq_shot_lb = QtGui.QLabel(self.seq_sa_widget)
        self.seq_shot_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.seq_shot_lb.setObjectName("seq_shot_lb")
        self.seq_grid.addWidget(self.seq_shot_lb, 4, 0, 1, 1)
        self.seq_desc_pte = QtGui.QPlainTextEdit(self.seq_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.seq_desc_pte.sizePolicy().hasHeightForWidth())
        self.seq_desc_pte.setSizePolicy(sizePolicy)
        self.seq_desc_pte.setObjectName("seq_desc_pte")
        self.seq_grid.addWidget(self.seq_desc_pte, 3, 1, 1, 1)
        self.seq_shot_tablev = QtGui.QTableView(self.seq_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.seq_shot_tablev.sizePolicy().hasHeightForWidth())
        self.seq_shot_tablev.setSizePolicy(sizePolicy)
        self.seq_shot_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.seq_shot_tablev.setObjectName("seq_shot_tablev")
        self.seq_grid.addWidget(self.seq_shot_tablev, 4, 1, 1, 1)
        self.seq_shot_btns_hbox = QtGui.QHBoxLayout()
        self.seq_shot_btns_hbox.setObjectName("seq_shot_btns_hbox")
        self.seq_shot_view_pb = QtGui.QPushButton(self.seq_sa_widget)
        self.seq_shot_view_pb.setObjectName("seq_shot_view_pb")
        self.seq_shot_btns_hbox.addWidget(self.seq_shot_view_pb)
        self.seq_shot_create_pb = QtGui.QPushButton(self.seq_sa_widget)
        self.seq_shot_create_pb.setObjectName("seq_shot_create_pb")
        self.seq_shot_btns_hbox.addWidget(self.seq_shot_create_pb)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.seq_shot_btns_hbox.addItem(spacerItem5)
        self.seq_grid.addLayout(self.seq_shot_btns_hbox, 5, 1, 1, 1)
        self.seq_prj_hbox = QtGui.QHBoxLayout()
        self.seq_prj_hbox.setObjectName("seq_prj_hbox")
        self.seq_prj_le = QtGui.QLineEdit(self.seq_sa_widget)
        self.seq_prj_le.setReadOnly(True)
        self.seq_prj_le.setObjectName("seq_prj_le")
        self.seq_prj_hbox.addWidget(self.seq_prj_le)
        self.seq_prj_view_pb = QtGui.QPushButton(self.seq_sa_widget)
        self.seq_prj_view_pb.setObjectName("seq_prj_view_pb")
        self.seq_prj_hbox.addWidget(self.seq_prj_view_pb)
        self.seq_grid.addLayout(self.seq_prj_hbox, 1, 1, 1, 1)
        self.seq_prj_lb = QtGui.QLabel(self.seq_sa_widget)
        self.seq_prj_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.seq_prj_lb.setObjectName("seq_prj_lb")
        self.seq_grid.addWidget(self.seq_prj_lb, 1, 0, 1, 1)
        self.seq_sa.setWidget(self.seq_sa_widget)
        self.seq_vbox.addWidget(self.seq_sa)
        self.pages_tabw.addTab(self.seq_widget, "")
        self.shot_widget = QtGui.QWidget()
        self.shot_widget.setObjectName("shot_widget")
        self.shot_vbox = QtGui.QVBoxLayout(self.shot_widget)
        self.shot_vbox.setObjectName("shot_vbox")
        self.shot_sa = QtGui.QScrollArea(self.shot_widget)
        self.shot_sa.setWidgetResizable(True)
        self.shot_sa.setObjectName("shot_sa")
        self.shot_sa_widget = QtGui.QWidget()
        self.shot_sa_widget.setGeometry(QtCore.QRect(0, 0, 1321, 963))
        self.shot_sa_widget.setObjectName("shot_sa_widget")
        self.shot_sa_widget_grid = QtGui.QGridLayout(self.shot_sa_widget)
        self.shot_sa_widget_grid.setObjectName("shot_sa_widget_grid")
        self.shot_seq_hbox = QtGui.QHBoxLayout()
        self.shot_seq_hbox.setObjectName("shot_seq_hbox")
        self.shot_seq_le = QtGui.QLineEdit(self.shot_sa_widget)
        self.shot_seq_le.setReadOnly(True)
        self.shot_seq_le.setObjectName("shot_seq_le")
        self.shot_seq_hbox.addWidget(self.shot_seq_le)
        self.shot_seq_view_pb = QtGui.QPushButton(self.shot_sa_widget)
        self.shot_seq_view_pb.setObjectName("shot_seq_view_pb")
        self.shot_seq_hbox.addWidget(self.shot_seq_view_pb)
        self.shot_sa_widget_grid.addLayout(self.shot_seq_hbox, 4, 1, 1, 1)
        self.shot_task_tablev = QtGui.QTableView(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.shot_task_tablev.sizePolicy().hasHeightForWidth())
        self.shot_task_tablev.setSizePolicy(sizePolicy)
        self.shot_task_tablev.setMinimumSize(QtCore.QSize(0, 300))
        self.shot_task_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.shot_task_tablev.setObjectName("shot_task_tablev")
        self.shot_sa_widget_grid.addWidget(self.shot_task_tablev, 12, 1, 1, 1)
        self.shot_desc_pte = QtGui.QPlainTextEdit(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.shot_desc_pte.sizePolicy().hasHeightForWidth())
        self.shot_desc_pte.setSizePolicy(sizePolicy)
        self.shot_desc_pte.setMinimumSize(QtCore.QSize(0, 125))
        self.shot_desc_pte.setObjectName("shot_desc_pte")
        self.shot_sa_widget_grid.addWidget(self.shot_desc_pte, 9, 1, 1, 1)
        self.shot_name_le = QtGui.QLineEdit(self.shot_sa_widget)
        self.shot_name_le.setReadOnly(True)
        self.shot_name_le.setObjectName("shot_name_le")
        self.shot_sa_widget_grid.addWidget(self.shot_name_le, 0, 1, 1, 1)
        self.shot_asset_lb = QtGui.QLabel(self.shot_sa_widget)
        self.shot_asset_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.shot_asset_lb.setObjectName("shot_asset_lb")
        self.shot_sa_widget_grid.addWidget(self.shot_asset_lb, 10, 0, 1, 1)
        self.shot_task_lb = QtGui.QLabel(self.shot_sa_widget)
        self.shot_task_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.shot_task_lb.setObjectName("shot_task_lb")
        self.shot_sa_widget_grid.addWidget(self.shot_task_lb, 12, 0, 1, 1)
        self.shot_desc_lb = QtGui.QLabel(self.shot_sa_widget)
        self.shot_desc_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.shot_desc_lb.setObjectName("shot_desc_lb")
        self.shot_sa_widget_grid.addWidget(self.shot_desc_lb, 9, 0, 1, 1)
        self.shot_name_lb = QtGui.QLabel(self.shot_sa_widget)
        self.shot_name_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shot_name_lb.setObjectName("shot_name_lb")
        self.shot_sa_widget_grid.addWidget(self.shot_name_lb, 0, 0, 1, 1)
        self.shot_seq_lb = QtGui.QLabel(self.shot_sa_widget)
        self.shot_seq_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shot_seq_lb.setObjectName("shot_seq_lb")
        self.shot_sa_widget_grid.addWidget(self.shot_seq_lb, 4, 0, 1, 1)
        self.shot_prj_lb = QtGui.QLabel(self.shot_sa_widget)
        self.shot_prj_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shot_prj_lb.setObjectName("shot_prj_lb")
        self.shot_sa_widget_grid.addWidget(self.shot_prj_lb, 1, 0, 1, 1)
        self.shot_prj_hbox = QtGui.QHBoxLayout()
        self.shot_prj_hbox.setObjectName("shot_prj_hbox")
        self.shot_prj_le = QtGui.QLineEdit(self.shot_sa_widget)
        self.shot_prj_le.setReadOnly(True)
        self.shot_prj_le.setObjectName("shot_prj_le")
        self.shot_prj_hbox.addWidget(self.shot_prj_le)
        self.shot_prj_view_pb = QtGui.QPushButton(self.shot_sa_widget)
        self.shot_prj_view_pb.setObjectName("shot_prj_view_pb")
        self.shot_prj_hbox.addWidget(self.shot_prj_view_pb)
        self.shot_sa_widget_grid.addLayout(self.shot_prj_hbox, 1, 1, 1, 1)
        self.shot_asset_btns_hbox = QtGui.QHBoxLayout()
        self.shot_asset_btns_hbox.setObjectName("shot_asset_btns_hbox")
        self.shot_asset_view_pb = QtGui.QPushButton(self.shot_sa_widget)
        self.shot_asset_view_pb.setObjectName("shot_asset_view_pb")
        self.shot_asset_btns_hbox.addWidget(self.shot_asset_view_pb)
        self.shot_asset_add_pb = QtGui.QPushButton(self.shot_sa_widget)
        self.shot_asset_add_pb.setObjectName("shot_asset_add_pb")
        self.shot_asset_btns_hbox.addWidget(self.shot_asset_add_pb)
        self.shot_asset_remove_pb = QtGui.QPushButton(self.shot_sa_widget)
        self.shot_asset_remove_pb.setObjectName("shot_asset_remove_pb")
        self.shot_asset_btns_hbox.addWidget(self.shot_asset_remove_pb)
        self.shot_asset_create_pb = QtGui.QPushButton(self.shot_sa_widget)
        self.shot_asset_create_pb.setObjectName("shot_asset_create_pb")
        self.shot_asset_btns_hbox.addWidget(self.shot_asset_create_pb)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.shot_asset_btns_hbox.addItem(spacerItem6)
        self.shot_sa_widget_grid.addLayout(self.shot_asset_btns_hbox, 11, 1, 1, 1)
        self.shot_task_btns_hbox = QtGui.QHBoxLayout()
        self.shot_task_btns_hbox.setObjectName("shot_task_btns_hbox")
        self.shot_task_view_pb = QtGui.QPushButton(self.shot_sa_widget)
        self.shot_task_view_pb.setObjectName("shot_task_view_pb")
        self.shot_task_btns_hbox.addWidget(self.shot_task_view_pb)
        self.shot_task_create_pb = QtGui.QPushButton(self.shot_sa_widget)
        self.shot_task_create_pb.setObjectName("shot_task_create_pb")
        self.shot_task_btns_hbox.addWidget(self.shot_task_create_pb)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.shot_task_btns_hbox.addItem(spacerItem7)
        self.shot_sa_widget_grid.addLayout(self.shot_task_btns_hbox, 13, 1, 1, 1)
        self.shot_frames_hbox = QtGui.QHBoxLayout()
        self.shot_frames_hbox.setObjectName("shot_frames_hbox")
        self.shot_start_lb = QtGui.QLabel(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_start_lb.sizePolicy().hasHeightForWidth())
        self.shot_start_lb.setSizePolicy(sizePolicy)
        self.shot_start_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shot_start_lb.setObjectName("shot_start_lb")
        self.shot_frames_hbox.addWidget(self.shot_start_lb)
        self.shot_start_sb = QtGui.QSpinBox(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_start_sb.sizePolicy().hasHeightForWidth())
        self.shot_start_sb.setSizePolicy(sizePolicy)
        self.shot_start_sb.setMinimum(-99999)
        self.shot_start_sb.setMaximum(99999)
        self.shot_start_sb.setProperty("value", 1001)
        self.shot_start_sb.setObjectName("shot_start_sb")
        self.shot_frames_hbox.addWidget(self.shot_start_sb)
        self.shot_end_lb = QtGui.QLabel(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_end_lb.sizePolicy().hasHeightForWidth())
        self.shot_end_lb.setSizePolicy(sizePolicy)
        self.shot_end_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shot_end_lb.setObjectName("shot_end_lb")
        self.shot_frames_hbox.addWidget(self.shot_end_lb)
        self.shot_end_sb = QtGui.QSpinBox(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_end_sb.sizePolicy().hasHeightForWidth())
        self.shot_end_sb.setSizePolicy(sizePolicy)
        self.shot_end_sb.setMinimum(-99999)
        self.shot_end_sb.setMaximum(99999)
        self.shot_end_sb.setProperty("value", 1050)
        self.shot_end_sb.setObjectName("shot_end_sb")
        self.shot_frames_hbox.addWidget(self.shot_end_sb)
        self.shot_handle_lb = QtGui.QLabel(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_handle_lb.sizePolicy().hasHeightForWidth())
        self.shot_handle_lb.setSizePolicy(sizePolicy)
        self.shot_handle_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.shot_handle_lb.setObjectName("shot_handle_lb")
        self.shot_frames_hbox.addWidget(self.shot_handle_lb)
        self.shot_handle_sb = QtGui.QSpinBox(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_handle_sb.sizePolicy().hasHeightForWidth())
        self.shot_handle_sb.setSizePolicy(sizePolicy)
        self.shot_handle_sb.setMinimum(-99999)
        self.shot_handle_sb.setMaximum(99999)
        self.shot_handle_sb.setProperty("value", 8)
        self.shot_handle_sb.setObjectName("shot_handle_sb")
        self.shot_frames_hbox.addWidget(self.shot_handle_sb)
        spacerItem8 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.shot_frames_hbox.addItem(spacerItem8)
        self.shot_sa_widget_grid.addLayout(self.shot_frames_hbox, 5, 1, 1, 1)
        self.shot_asset_treev = QtGui.QTreeView(self.shot_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.shot_asset_treev.sizePolicy().hasHeightForWidth())
        self.shot_asset_treev.setSizePolicy(sizePolicy)
        self.shot_asset_treev.setMinimumSize(QtCore.QSize(0, 300))
        self.shot_asset_treev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.shot_asset_treev.setObjectName("shot_asset_treev")
        self.shot_sa_widget_grid.addWidget(self.shot_asset_treev, 10, 1, 1, 1)
        self.shot_sa.setWidget(self.shot_sa_widget)
        self.shot_vbox.addWidget(self.shot_sa)
        self.pages_tabw.addTab(self.shot_widget, "")
        self.atype_widget = QtGui.QWidget()
        self.atype_widget.setObjectName("atype_widget")
        self.atype_vbox = QtGui.QVBoxLayout(self.atype_widget)
        self.atype_vbox.setObjectName("atype_vbox")
        self.atype_sa = QtGui.QScrollArea(self.atype_widget)
        self.atype_sa.setWidgetResizable(True)
        self.atype_sa.setObjectName("atype_sa")
        self.atype_sa_widget = QtGui.QWidget()
        self.atype_sa_widget.setGeometry(QtCore.QRect(0, 0, 1337, 931))
        self.atype_sa_widget.setObjectName("atype_sa_widget")
        self.atype_sa_widget_grid = QtGui.QGridLayout(self.atype_sa_widget)
        self.atype_sa_widget_grid.setObjectName("atype_sa_widget_grid")
        self.atype_desc_lb = QtGui.QLabel(self.atype_sa_widget)
        self.atype_desc_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.atype_desc_lb.setObjectName("atype_desc_lb")
        self.atype_sa_widget_grid.addWidget(self.atype_desc_lb, 1, 0, 1, 1)
        self.atype_name_lb = QtGui.QLabel(self.atype_sa_widget)
        self.atype_name_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.atype_name_lb.setObjectName("atype_name_lb")
        self.atype_sa_widget_grid.addWidget(self.atype_name_lb, 0, 0, 1, 1)
        self.atype_name_le = QtGui.QLineEdit(self.atype_sa_widget)
        self.atype_name_le.setReadOnly(True)
        self.atype_name_le.setObjectName("atype_name_le")
        self.atype_sa_widget_grid.addWidget(self.atype_name_le, 0, 1, 1, 1)
        self.atype_desc_pte = QtGui.QPlainTextEdit(self.atype_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.atype_desc_pte.sizePolicy().hasHeightForWidth())
        self.atype_desc_pte.setSizePolicy(sizePolicy)
        self.atype_desc_pte.setObjectName("atype_desc_pte")
        self.atype_sa_widget_grid.addWidget(self.atype_desc_pte, 1, 1, 1, 1)
        self.atype_asset_lb = QtGui.QLabel(self.atype_sa_widget)
        self.atype_asset_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.atype_asset_lb.setObjectName("atype_asset_lb")
        self.atype_sa_widget_grid.addWidget(self.atype_asset_lb, 2, 0, 1, 1)
        self.atype_asset_treev = QtGui.QTreeView(self.atype_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.atype_asset_treev.sizePolicy().hasHeightForWidth())
        self.atype_asset_treev.setSizePolicy(sizePolicy)
        self.atype_asset_treev.setObjectName("atype_asset_treev")
        self.atype_sa_widget_grid.addWidget(self.atype_asset_treev, 2, 1, 1, 1)
        self.atype_asset_btns_hbox = QtGui.QHBoxLayout()
        self.atype_asset_btns_hbox.setObjectName("atype_asset_btns_hbox")
        self.atype_asset_view_pb = QtGui.QPushButton(self.atype_sa_widget)
        self.atype_asset_view_pb.setObjectName("atype_asset_view_pb")
        self.atype_asset_btns_hbox.addWidget(self.atype_asset_view_pb)
        self.atype_asset_create_pb = QtGui.QPushButton(self.atype_sa_widget)
        self.atype_asset_create_pb.setObjectName("atype_asset_create_pb")
        self.atype_asset_btns_hbox.addWidget(self.atype_asset_create_pb)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.atype_asset_btns_hbox.addItem(spacerItem9)
        self.atype_sa_widget_grid.addLayout(self.atype_asset_btns_hbox, 3, 1, 1, 1)
        self.atype_sa.setWidget(self.atype_sa_widget)
        self.atype_vbox.addWidget(self.atype_sa)
        self.pages_tabw.addTab(self.atype_widget, "")
        self.asset_widget = QtGui.QWidget()
        self.asset_widget.setObjectName("asset_widget")
        self.asset_vbox = QtGui.QVBoxLayout(self.asset_widget)
        self.asset_vbox.setObjectName("asset_vbox")
        self.asset_sa = QtGui.QScrollArea(self.asset_widget)
        self.asset_sa.setWidgetResizable(True)
        self.asset_sa.setObjectName("asset_sa")
        self.asset_sa_widget = QtGui.QWidget()
        self.asset_sa_widget.setGeometry(QtCore.QRect(0, 0, 1337, 931))
        self.asset_sa_widget.setObjectName("asset_sa_widget")
        self.asset_sa_widget_grid = QtGui.QGridLayout(self.asset_sa_widget)
        self.asset_sa_widget_grid.setObjectName("asset_sa_widget_grid")
        self.asset_asset_btns_hbox = QtGui.QHBoxLayout()
        self.asset_asset_btns_hbox.setObjectName("asset_asset_btns_hbox")
        self.asset_asset_view_pb = QtGui.QPushButton(self.asset_sa_widget)
        self.asset_asset_view_pb.setObjectName("asset_asset_view_pb")
        self.asset_asset_btns_hbox.addWidget(self.asset_asset_view_pb)
        self.asset_asset_add_pb = QtGui.QPushButton(self.asset_sa_widget)
        self.asset_asset_add_pb.setObjectName("asset_asset_add_pb")
        self.asset_asset_btns_hbox.addWidget(self.asset_asset_add_pb)
        self.asset_asset_remove_pb = QtGui.QPushButton(self.asset_sa_widget)
        self.asset_asset_remove_pb.setObjectName("asset_asset_remove_pb")
        self.asset_asset_btns_hbox.addWidget(self.asset_asset_remove_pb)
        self.asset_asset_create_pb = QtGui.QPushButton(self.asset_sa_widget)
        self.asset_asset_create_pb.setObjectName("asset_asset_create_pb")
        self.asset_asset_btns_hbox.addWidget(self.asset_asset_create_pb)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.asset_asset_btns_hbox.addItem(spacerItem10)
        self.asset_sa_widget_grid.addLayout(self.asset_asset_btns_hbox, 7, 1, 1, 1)
        self.asset_task_btns_hbox = QtGui.QHBoxLayout()
        self.asset_task_btns_hbox.setObjectName("asset_task_btns_hbox")
        self.asset_task_view_pb = QtGui.QPushButton(self.asset_sa_widget)
        self.asset_task_view_pb.setObjectName("asset_task_view_pb")
        self.asset_task_btns_hbox.addWidget(self.asset_task_view_pb)
        self.asset_task_create_pb = QtGui.QPushButton(self.asset_sa_widget)
        self.asset_task_create_pb.setObjectName("asset_task_create_pb")
        self.asset_task_btns_hbox.addWidget(self.asset_task_create_pb)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.asset_task_btns_hbox.addItem(spacerItem11)
        self.asset_sa_widget_grid.addLayout(self.asset_task_btns_hbox, 9, 1, 1, 1)
        self.asset_atype_hbox = QtGui.QHBoxLayout()
        self.asset_atype_hbox.setObjectName("asset_atype_hbox")
        self.asset_atype_le = QtGui.QLineEdit(self.asset_sa_widget)
        self.asset_atype_le.setReadOnly(True)
        self.asset_atype_le.setObjectName("asset_atype_le")
        self.asset_atype_hbox.addWidget(self.asset_atype_le)
        self.asset_atype_view_pb = QtGui.QPushButton(self.asset_sa_widget)
        self.asset_atype_view_pb.setObjectName("asset_atype_view_pb")
        self.asset_atype_hbox.addWidget(self.asset_atype_view_pb)
        self.asset_sa_widget_grid.addLayout(self.asset_atype_hbox, 3, 1, 1, 1)
        self.asset_desc_lb = QtGui.QLabel(self.asset_sa_widget)
        self.asset_desc_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.asset_desc_lb.setObjectName("asset_desc_lb")
        self.asset_sa_widget_grid.addWidget(self.asset_desc_lb, 5, 0, 1, 1)
        self.asset_asset_lb = QtGui.QLabel(self.asset_sa_widget)
        self.asset_asset_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.asset_asset_lb.setObjectName("asset_asset_lb")
        self.asset_sa_widget_grid.addWidget(self.asset_asset_lb, 6, 0, 1, 1)
        self.asset_task_lb = QtGui.QLabel(self.asset_sa_widget)
        self.asset_task_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.asset_task_lb.setObjectName("asset_task_lb")
        self.asset_sa_widget_grid.addWidget(self.asset_task_lb, 8, 0, 1, 1)
        self.asset_name_lb = QtGui.QLabel(self.asset_sa_widget)
        self.asset_name_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.asset_name_lb.setObjectName("asset_name_lb")
        self.asset_sa_widget_grid.addWidget(self.asset_name_lb, 0, 0, 1, 1)
        self.asset_name_le = QtGui.QLineEdit(self.asset_sa_widget)
        self.asset_name_le.setReadOnly(True)
        self.asset_name_le.setObjectName("asset_name_le")
        self.asset_sa_widget_grid.addWidget(self.asset_name_le, 0, 1, 1, 1)
        self.asset_desc_pte = QtGui.QPlainTextEdit(self.asset_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.asset_desc_pte.sizePolicy().hasHeightForWidth())
        self.asset_desc_pte.setSizePolicy(sizePolicy)
        self.asset_desc_pte.setMinimumSize(QtCore.QSize(0, 125))
        self.asset_desc_pte.setObjectName("asset_desc_pte")
        self.asset_sa_widget_grid.addWidget(self.asset_desc_pte, 5, 1, 1, 1)
        self.asset_task_tablev = QtGui.QTableView(self.asset_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.asset_task_tablev.sizePolicy().hasHeightForWidth())
        self.asset_task_tablev.setSizePolicy(sizePolicy)
        self.asset_task_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.asset_task_tablev.setObjectName("asset_task_tablev")
        self.asset_sa_widget_grid.addWidget(self.asset_task_tablev, 8, 1, 1, 1)
        self.asset_atype_lb = QtGui.QLabel(self.asset_sa_widget)
        self.asset_atype_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.asset_atype_lb.setObjectName("asset_atype_lb")
        self.asset_sa_widget_grid.addWidget(self.asset_atype_lb, 3, 0, 1, 1)
        self.asset_prj_hbox = QtGui.QHBoxLayout()
        self.asset_prj_hbox.setObjectName("asset_prj_hbox")
        self.asset_prj_le = QtGui.QLineEdit(self.asset_sa_widget)
        self.asset_prj_le.setReadOnly(True)
        self.asset_prj_le.setObjectName("asset_prj_le")
        self.asset_prj_hbox.addWidget(self.asset_prj_le)
        self.asset_prj_view_pb = QtGui.QPushButton(self.asset_sa_widget)
        self.asset_prj_view_pb.setObjectName("asset_prj_view_pb")
        self.asset_prj_hbox.addWidget(self.asset_prj_view_pb)
        self.asset_sa_widget_grid.addLayout(self.asset_prj_hbox, 1, 1, 1, 1)
        self.asset_prj_lb = QtGui.QLabel(self.asset_sa_widget)
        self.asset_prj_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.asset_prj_lb.setObjectName("asset_prj_lb")
        self.asset_sa_widget_grid.addWidget(self.asset_prj_lb, 1, 0, 1, 1)
        self.asset_asset_treev = QtGui.QTreeView(self.asset_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.asset_asset_treev.sizePolicy().hasHeightForWidth())
        self.asset_asset_treev.setSizePolicy(sizePolicy)
        self.asset_asset_treev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.asset_asset_treev.setObjectName("asset_asset_treev")
        self.asset_sa_widget_grid.addWidget(self.asset_asset_treev, 6, 1, 1, 1)
        self.asset_sa.setWidget(self.asset_sa_widget)
        self.asset_vbox.addWidget(self.asset_sa)
        self.pages_tabw.addTab(self.asset_widget, "")
        self.dep_widget = QtGui.QWidget()
        self.dep_widget.setObjectName("dep_widget")
        self.dep_vbox = QtGui.QVBoxLayout(self.dep_widget)
        self.dep_vbox.setObjectName("dep_vbox")
        self.dep_sa = QtGui.QScrollArea(self.dep_widget)
        self.dep_sa.setWidgetResizable(True)
        self.dep_sa.setObjectName("dep_sa")
        self.dep_sa_widget = QtGui.QWidget()
        self.dep_sa_widget.setGeometry(QtCore.QRect(0, 0, 1337, 931))
        self.dep_sa_widget.setObjectName("dep_sa_widget")
        self.dep_sa_widget_grid = QtGui.QGridLayout(self.dep_sa_widget)
        self.dep_sa_widget_grid.setObjectName("dep_sa_widget_grid")
        self.dep_ordervalue_lb = QtGui.QLabel(self.dep_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep_ordervalue_lb.sizePolicy().hasHeightForWidth())
        self.dep_ordervalue_lb.setSizePolicy(sizePolicy)
        self.dep_ordervalue_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dep_ordervalue_lb.setObjectName("dep_ordervalue_lb")
        self.dep_sa_widget_grid.addWidget(self.dep_ordervalue_lb, 3, 0, 1, 1)
        self.dep_short_lb = QtGui.QLabel(self.dep_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep_short_lb.sizePolicy().hasHeightForWidth())
        self.dep_short_lb.setSizePolicy(sizePolicy)
        self.dep_short_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dep_short_lb.setObjectName("dep_short_lb")
        self.dep_sa_widget_grid.addWidget(self.dep_short_lb, 1, 0, 1, 1)
        self.dep_name_lb = QtGui.QLabel(self.dep_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep_name_lb.sizePolicy().hasHeightForWidth())
        self.dep_name_lb.setSizePolicy(sizePolicy)
        self.dep_name_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dep_name_lb.setObjectName("dep_name_lb")
        self.dep_sa_widget_grid.addWidget(self.dep_name_lb, 0, 0, 1, 1)
        self.dep_desc_lb = QtGui.QLabel(self.dep_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep_desc_lb.sizePolicy().hasHeightForWidth())
        self.dep_desc_lb.setSizePolicy(sizePolicy)
        self.dep_desc_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dep_desc_lb.setObjectName("dep_desc_lb")
        self.dep_sa_widget_grid.addWidget(self.dep_desc_lb, 2, 0, 1, 1)
        self.dep_prj_lb = QtGui.QLabel(self.dep_sa_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep_prj_lb.sizePolicy().hasHeightForWidth())
        self.dep_prj_lb.setSizePolicy(sizePolicy)
        self.dep_prj_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dep_prj_lb.setObjectName("dep_prj_lb")
        self.dep_sa_widget_grid.addWidget(self.dep_prj_lb, 6, 0, 1, 1)
        self.dep_prj_btns_hbox = QtGui.QHBoxLayout()
        self.dep_prj_btns_hbox.setObjectName("dep_prj_btns_hbox")
        self.dep_prj_view_pb = QtGui.QPushButton(self.dep_sa_widget)
        self.dep_prj_view_pb.setObjectName("dep_prj_view_pb")
        self.dep_prj_btns_hbox.addWidget(self.dep_prj_view_pb)
        self.dep_prj_add_pb = QtGui.QPushButton(self.dep_sa_widget)
        self.dep_prj_add_pb.setObjectName("dep_prj_add_pb")
        self.dep_prj_btns_hbox.addWidget(self.dep_prj_add_pb)
        self.dep_prj_remove_pb = QtGui.QPushButton(self.dep_sa_widget)
        self.dep_prj_remove_pb.setObjectName("dep_prj_remove_pb")
        self.dep_prj_btns_hbox.addWidget(self.dep_prj_remove_pb)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.dep_prj_btns_hbox.addItem(spacerItem12)
        self.dep_sa_widget_grid.addLayout(self.dep_prj_btns_hbox, 7, 1, 1, 1)
        self.dep_assetflag_hbox = QtGui.QHBoxLayout()
        self.dep_assetflag_hbox.setObjectName("dep_assetflag_hbox")
        self.dep_shot_rb = QtGui.QRadioButton(self.dep_sa_widget)
        self.dep_shot_rb.setEnabled(False)
        self.dep_shot_rb.setCheckable(True)
        self.dep_shot_rb.setChecked(True)
        self.dep_shot_rb.setObjectName("dep_shot_rb")
        self.dep_assetflag_hbox.addWidget(self.dep_shot_rb)
        self.dep_asset_rb = QtGui.QRadioButton(self.dep_sa_widget)
        self.dep_asset_rb.setEnabled(False)
        self.dep_asset_rb.setCheckable(True)
        self.dep_asset_rb.setObjectName("dep_asset_rb")
        self.dep_assetflag_hbox.addWidget(self.dep_asset_rb)
        spacerItem13 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.dep_assetflag_hbox.addItem(spacerItem13)
        self.dep_sa_widget_grid.addLayout(self.dep_assetflag_hbox, 4, 1, 1, 1)
        self.dep_ordervalue_sb = QtGui.QSpinBox(self.dep_sa_widget)
        self.dep_ordervalue_sb.setMinimum(-9999)
        self.dep_ordervalue_sb.setMaximum(999999)
        self.dep_ordervalue_sb.setObjectName("dep_ordervalue_sb")
        self.dep_sa_widget_grid.addWidget(self.dep_ordervalue_sb, 3, 1, 1, 1)
        self.dep_desc_pte = QtGui.QPlainTextEdit(self.dep_sa_widget)
        self.dep_desc_pte.setMinimumSize(QtCore.QSize(0, 125))
        self.dep_desc_pte.setMaximumSize(QtCore.QSize(16777215, 125))
        self.dep_desc_pte.setObjectName("dep_desc_pte")
        self.dep_sa_widget_grid.addWidget(self.dep_desc_pte, 2, 1, 1, 1)
        self.dep_short_le = QtGui.QLineEdit(self.dep_sa_widget)
        self.dep_short_le.setReadOnly(True)
        self.dep_short_le.setObjectName("dep_short_le")
        self.dep_sa_widget_grid.addWidget(self.dep_short_le, 1, 1, 1, 1)
        self.dep_name_le = QtGui.QLineEdit(self.dep_sa_widget)
        self.dep_name_le.setReadOnly(True)
        self.dep_name_le.setObjectName("dep_name_le")
        self.dep_sa_widget_grid.addWidget(self.dep_name_le, 0, 1, 1, 1)
        self.dep_prj_tablev = QtGui.QTableView(self.dep_sa_widget)
        self.dep_prj_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.dep_prj_tablev.setObjectName("dep_prj_tablev")
        self.dep_sa_widget_grid.addWidget(self.dep_prj_tablev, 6, 1, 1, 1)
        self.dep_sa.setWidget(self.dep_sa_widget)
        self.dep_vbox.addWidget(self.dep_sa)
        self.pages_tabw.addTab(self.dep_widget, "")
        self.task_widget = QtGui.QWidget()
        self.task_widget.setObjectName("task_widget")
        self.task_vbox = QtGui.QVBoxLayout(self.task_widget)
        self.task_vbox.setObjectName("task_vbox")
        self.task_sa = QtGui.QScrollArea(self.task_widget)
        self.task_sa.setWidgetResizable(True)
        self.task_sa.setObjectName("task_sa")
        self.task_sa_widget = QtGui.QWidget()
        self.task_sa_widget.setGeometry(QtCore.QRect(0, 0, 1337, 931))
        self.task_sa_widget.setObjectName("task_sa_widget")
        self.gridLayout_7 = QtGui.QGridLayout(self.task_sa_widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.task_user_btns_hbox = QtGui.QHBoxLayout()
        self.task_user_btns_hbox.setObjectName("task_user_btns_hbox")
        self.task_user_view_pb = QtGui.QPushButton(self.task_sa_widget)
        self.task_user_view_pb.setObjectName("task_user_view_pb")
        self.task_user_btns_hbox.addWidget(self.task_user_view_pb)
        self.task_user_add_pb = QtGui.QPushButton(self.task_sa_widget)
        self.task_user_add_pb.setObjectName("task_user_add_pb")
        self.task_user_btns_hbox.addWidget(self.task_user_add_pb)
        self.task_user_remove_pb = QtGui.QPushButton(self.task_sa_widget)
        self.task_user_remove_pb.setObjectName("task_user_remove_pb")
        self.task_user_btns_hbox.addWidget(self.task_user_remove_pb)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.task_user_btns_hbox.addItem(spacerItem14)
        self.gridLayout_7.addLayout(self.task_user_btns_hbox, 7, 1, 1, 1)
        self.task_user_lb = QtGui.QLabel(self.task_sa_widget)
        self.task_user_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.task_user_lb.setObjectName("task_user_lb")
        self.gridLayout_7.addWidget(self.task_user_lb, 6, 0, 1, 1)
        self.task_deadline_lb = QtGui.QLabel(self.task_sa_widget)
        self.task_deadline_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.task_deadline_lb.setObjectName("task_deadline_lb")
        self.gridLayout_7.addWidget(self.task_deadline_lb, 3, 0, 1, 1)
        self.task_status_lb = QtGui.QLabel(self.task_sa_widget)
        self.task_status_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.task_status_lb.setObjectName("task_status_lb")
        self.gridLayout_7.addWidget(self.task_status_lb, 2, 0, 1, 1)
        self.task_status_cb = QtGui.QComboBox(self.task_sa_widget)
        self.task_status_cb.setObjectName("task_status_cb")
        self.task_status_cb.addItem("")
        self.task_status_cb.addItem("")
        self.task_status_cb.addItem("")
        self.gridLayout_7.addWidget(self.task_status_cb, 2, 1, 1, 1)
        self.task_deadline_de = QtGui.QDateEdit(self.task_sa_widget)
        self.task_deadline_de.setDate(QtCore.QDate(2015, 1, 1))
        self.task_deadline_de.setObjectName("task_deadline_de")
        self.gridLayout_7.addWidget(self.task_deadline_de, 3, 1, 1, 1)
        self.task_link_hbox = QtGui.QHBoxLayout()
        self.task_link_hbox.setObjectName("task_link_hbox")
        self.task_link_le = QtGui.QLineEdit(self.task_sa_widget)
        self.task_link_le.setReadOnly(True)
        self.task_link_le.setObjectName("task_link_le")
        self.task_link_hbox.addWidget(self.task_link_le)
        self.task_link_view_pb = QtGui.QPushButton(self.task_sa_widget)
        self.task_link_view_pb.setObjectName("task_link_view_pb")
        self.task_link_hbox.addWidget(self.task_link_view_pb)
        self.gridLayout_7.addLayout(self.task_link_hbox, 4, 1, 1, 1)
        self.task_link_lb = QtGui.QLabel(self.task_sa_widget)
        self.task_link_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.task_link_lb.setObjectName("task_link_lb")
        self.gridLayout_7.addWidget(self.task_link_lb, 4, 0, 1, 1)
        self.task_dep_hbox = QtGui.QHBoxLayout()
        self.task_dep_hbox.setObjectName("task_dep_hbox")
        self.task_dep_le = QtGui.QLineEdit(self.task_sa_widget)
        self.task_dep_le.setReadOnly(True)
        self.task_dep_le.setObjectName("task_dep_le")
        self.task_dep_hbox.addWidget(self.task_dep_le)
        self.task_dep_view_pb = QtGui.QPushButton(self.task_sa_widget)
        self.task_dep_view_pb.setObjectName("task_dep_view_pb")
        self.task_dep_hbox.addWidget(self.task_dep_view_pb)
        self.gridLayout_7.addLayout(self.task_dep_hbox, 0, 1, 1, 1)
        self.task_dep_lb = QtGui.QLabel(self.task_sa_widget)
        self.task_dep_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.task_dep_lb.setObjectName("task_dep_lb")
        self.gridLayout_7.addWidget(self.task_dep_lb, 0, 0, 1, 1)
        self.task_user_tablev = QtGui.QTableView(self.task_sa_widget)
        self.task_user_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.task_user_tablev.setObjectName("task_user_tablev")
        self.gridLayout_7.addWidget(self.task_user_tablev, 6, 1, 1, 1)
        self.task_sa.setWidget(self.task_sa_widget)
        self.task_vbox.addWidget(self.task_sa)
        self.pages_tabw.addTab(self.task_widget, "")
        self.users_widget = QtGui.QWidget()
        self.users_widget.setObjectName("users_widget")
        self.users_vbox = QtGui.QVBoxLayout(self.users_widget)
        self.users_vbox.setObjectName("users_vbox")
        self.users_sa = QtGui.QScrollArea(self.users_widget)
        self.users_sa.setWidgetResizable(True)
        self.users_sa.setObjectName("users_sa")
        self.users_sa_widget = QtGui.QWidget()
        self.users_sa_widget.setGeometry(QtCore.QRect(0, 0, 1337, 931))
        self.users_sa_widget.setObjectName("users_sa_widget")
        self.users_sa_widget_vbox = QtGui.QVBoxLayout(self.users_sa_widget)
        self.users_sa_widget_vbox.setObjectName("users_sa_widget_vbox")
        self.users_tablev = QtGui.QTableView(self.users_sa_widget)
        self.users_tablev.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.users_tablev.setObjectName("users_tablev")
        self.users_sa_widget_vbox.addWidget(self.users_tablev)
        self.users_btns_hbox = QtGui.QHBoxLayout()
        self.users_btns_hbox.setObjectName("users_btns_hbox")
        self.users_user_view_pb = QtGui.QPushButton(self.users_sa_widget)
        self.users_user_view_pb.setObjectName("users_user_view_pb")
        self.users_btns_hbox.addWidget(self.users_user_view_pb)
        self.users_user_create_pb = QtGui.QPushButton(self.users_sa_widget)
        self.users_user_create_pb.setObjectName("users_user_create_pb")
        self.users_btns_hbox.addWidget(self.users_user_create_pb)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.users_btns_hbox.addItem(spacerItem15)
        self.users_sa_widget_vbox.addLayout(self.users_btns_hbox)
        self.users_sa.setWidget(self.users_sa_widget)
        self.users_vbox.addWidget(self.users_sa)
        self.pages_tabw.addTab(self.users_widget, "")
        self.user_widget = QtGui.QWidget()
        self.user_widget.setObjectName("user_widget")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.user_widget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.user_sa = QtGui.QScrollArea(self.user_widget)
        self.user_sa.setWidgetResizable(True)
        self.user_sa.setObjectName("user_sa")
        self.user_sa_widget = QtGui.QWidget()
        self.user_sa_widget.setGeometry(QtCore.QRect(0, 0, 1337, 931))
        self.user_sa_widget.setObjectName("user_sa_widget")
        self.user_sa_widget_grid = QtGui.QGridLayout(self.user_sa_widget)
        self.user_sa_widget_grid.setObjectName("user_sa_widget_grid")
        self.user_prj_btns_hbox = QtGui.QHBoxLayout()
        self.user_prj_btns_hbox.setObjectName("user_prj_btns_hbox")
        self.user_prj_view_pb = QtGui.QPushButton(self.user_sa_widget)
        self.user_prj_view_pb.setObjectName("user_prj_view_pb")
        self.user_prj_btns_hbox.addWidget(self.user_prj_view_pb)
        self.user_prj_add_pb = QtGui.QPushButton(self.user_sa_widget)
        self.user_prj_add_pb.setObjectName("user_prj_add_pb")
        self.user_prj_btns_hbox.addWidget(self.user_prj_add_pb)
        self.user_prj_remove_pb = QtGui.QPushButton(self.user_sa_widget)
        self.user_prj_remove_pb.setObjectName("user_prj_remove_pb")
        self.user_prj_btns_hbox.addWidget(self.user_prj_remove_pb)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.user_prj_btns_hbox.addItem(spacerItem16)
        self.user_sa_widget_grid.addLayout(self.user_prj_btns_hbox, 5, 1, 1, 1)
        self.user_last_lb = QtGui.QLabel(self.user_sa_widget)
        self.user_last_lb.setObjectName("user_last_lb")
        self.user_sa_widget_grid.addWidget(self.user_last_lb, 2, 0, 1, 1)
        self.user_username_lb = QtGui.QLabel(self.user_sa_widget)
        self.user_username_lb.setObjectName("user_username_lb")
        self.user_sa_widget_grid.addWidget(self.user_username_lb, 0, 0, 1, 1)
        self.user_email_lb = QtGui.QLabel(self.user_sa_widget)
        self.user_email_lb.setObjectName("user_email_lb")
        self.user_sa_widget_grid.addWidget(self.user_email_lb, 3, 0, 1, 1)
        self.user_first_lb = QtGui.QLabel(self.user_sa_widget)
        self.user_first_lb.setObjectName("user_first_lb")
        self.user_sa_widget_grid.addWidget(self.user_first_lb, 1, 0, 1, 1)
        self.user_username_le = QtGui.QLineEdit(self.user_sa_widget)
        self.user_username_le.setObjectName("user_username_le")
        self.user_sa_widget_grid.addWidget(self.user_username_le, 0, 1, 1, 1)
        self.user_first_le = QtGui.QLineEdit(self.user_sa_widget)
        self.user_first_le.setObjectName("user_first_le")
        self.user_sa_widget_grid.addWidget(self.user_first_le, 1, 1, 1, 1)
        self.user_email_le = QtGui.QLineEdit(self.user_sa_widget)
        self.user_email_le.setObjectName("user_email_le")
        self.user_sa_widget_grid.addWidget(self.user_email_le, 3, 1, 1, 1)
        self.user_last_le = QtGui.QLineEdit(self.user_sa_widget)
        self.user_last_le.setObjectName("user_last_le")
        self.user_sa_widget_grid.addWidget(self.user_last_le, 2, 1, 1, 1)
        self.user_prj_lb = QtGui.QLabel(self.user_sa_widget)
        self.user_prj_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.user_prj_lb.setObjectName("user_prj_lb")
        self.user_sa_widget_grid.addWidget(self.user_prj_lb, 4, 0, 1, 1)
        self.user_prj_tablev = QtGui.QTableView(self.user_sa_widget)
        self.user_prj_tablev.setObjectName("user_prj_tablev")
        self.user_sa_widget_grid.addWidget(self.user_prj_tablev, 4, 1, 1, 1)
        self.user_task_lb = QtGui.QLabel(self.user_sa_widget)
        self.user_task_lb.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.user_task_lb.setObjectName("user_task_lb")
        self.user_sa_widget_grid.addWidget(self.user_task_lb, 8, 0, 1, 1)
        self.user_task_btns_hbox = QtGui.QHBoxLayout()
        self.user_task_btns_hbox.setObjectName("user_task_btns_hbox")
        self.user_task_view_pb = QtGui.QPushButton(self.user_sa_widget)
        self.user_task_view_pb.setObjectName("user_task_view_pb")
        self.user_task_btns_hbox.addWidget(self.user_task_view_pb)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.user_task_btns_hbox.addItem(spacerItem17)
        self.user_sa_widget_grid.addLayout(self.user_task_btns_hbox, 9, 1, 1, 1)
        self.user_task_treev = QtGui.QTreeView(self.user_sa_widget)
        self.user_task_treev.setObjectName("user_task_treev")
        self.user_sa_widget_grid.addWidget(self.user_task_treev, 8, 1, 1, 1)
        self.user_sa.setWidget(self.user_sa_widget)
        self.verticalLayout_9.addWidget(self.user_sa)
        self.pages_tabw.addTab(self.user_widget, "")
        self.central_vbox.addWidget(self.pages_tabw)
        guerillamgmt_mwin.setCentralWidget(self.central_widget)
        self.statusbar = QtGui.QStatusBar(guerillamgmt_mwin)
        self.statusbar.setObjectName("statusbar")
        guerillamgmt_mwin.setStatusBar(self.statusbar)

        self.retranslateUi(guerillamgmt_mwin)
        self.pages_tabw.setCurrentIndex(0)
        self.prj_scale_cb.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(guerillamgmt_mwin)

    def retranslateUi(self, guerillamgmt_mwin):
        guerillamgmt_mwin.setWindowTitle(QtGui.QApplication.translate("guerillamgmt_mwin", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.prjs_prj_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.prjs_prj_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.prjs_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_users_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_fps_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Framerate", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_atype_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_atype_add_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_atype_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_short_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Short", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_desc_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_res_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_semester_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Semester", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_created_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Created", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_seq_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_name_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_cb.setItemText(0, QtGui.QApplication.translate("guerillamgmt_mwin", "millimeter", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_cb.setItemText(1, QtGui.QApplication.translate("guerillamgmt_mwin", "centimeter", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_cb.setItemText(2, QtGui.QApplication.translate("guerillamgmt_mwin", "meter", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_cb.setItemText(3, QtGui.QApplication.translate("guerillamgmt_mwin", "kilometer", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_cb.setItemText(4, QtGui.QApplication.translate("guerillamgmt_mwin", "inch", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_cb.setItemText(5, QtGui.QApplication.translate("guerillamgmt_mwin", "foot", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_cb.setItemText(6, QtGui.QApplication.translate("guerillamgmt_mwin", "yard", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_scale_cb.setItemText(7, QtGui.QApplication.translate("guerillamgmt_mwin", "mile", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_dep_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Departments", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_semester_le.setPlaceholderText(QtGui.QApplication.translate("guerillamgmt_mwin", "e.g. SS15 or WS15/16", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_atype_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Assettypes", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_seq_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_seq_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_dep_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_dep_add_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_dep_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_user_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_user_add_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_user_remove_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_user_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_path_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.prj_path_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.prj_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_desc_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_name_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_shot_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_shot_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_shot_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_prj_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.seq_prj_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.seq_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_seq_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_asset_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_task_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_desc_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_name_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_seq_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_prj_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_prj_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_asset_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_asset_add_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_asset_remove_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_asset_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_task_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_task_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_start_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_start_sb.setSuffix(QtGui.QApplication.translate("guerillamgmt_mwin", "f", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_end_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_end_sb.setSuffix(QtGui.QApplication.translate("guerillamgmt_mwin", "f", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_handle_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Handlesize", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_handle_sb.setToolTip(QtGui.QApplication.translate("guerillamgmt_mwin", "The pre and postroll.", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_handle_sb.setSuffix(QtGui.QApplication.translate("guerillamgmt_mwin", "f", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.shot_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.atype_desc_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.atype_name_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.atype_asset_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.atype_asset_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.atype_asset_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.atype_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Assettype", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_asset_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_asset_add_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_asset_remove_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_asset_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_task_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_task_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_atype_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_desc_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_asset_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_task_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_name_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_atype_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Assettype", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_prj_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_prj_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.asset_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_ordervalue_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Ordervalue", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_short_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Short", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_name_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_desc_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_prj_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_prj_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_prj_add_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_prj_remove_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_shot_rb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_asset_rb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Asset", None, QtGui.QApplication.UnicodeUTF8))
        self.dep_ordervalue_sb.setToolTip(QtGui.QApplication.translate("guerillamgmt_mwin", "A value for ordering the departments in the UIs. The default departments are have values from 10, 20, 30, 40...", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.dep_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Department", None, QtGui.QApplication.UnicodeUTF8))
        self.task_user_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.task_user_add_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.task_user_remove_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.task_user_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.task_deadline_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Deadline", None, QtGui.QApplication.UnicodeUTF8))
        self.task_status_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.task_status_cb.setItemText(0, QtGui.QApplication.translate("guerillamgmt_mwin", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.task_status_cb.setItemText(1, QtGui.QApplication.translate("guerillamgmt_mwin", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.task_status_cb.setItemText(2, QtGui.QApplication.translate("guerillamgmt_mwin", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.task_link_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.task_link_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Link", None, QtGui.QApplication.UnicodeUTF8))
        self.task_dep_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.task_dep_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Department", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.task_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.users_user_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.users_user_create_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.users_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "Users", None, QtGui.QApplication.UnicodeUTF8))
        self.user_prj_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.user_prj_add_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.user_prj_remove_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.user_last_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Last", None, QtGui.QApplication.UnicodeUTF8))
        self.user_username_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.user_email_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Email", None, QtGui.QApplication.UnicodeUTF8))
        self.user_first_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "First", None, QtGui.QApplication.UnicodeUTF8))
        self.user_prj_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.user_task_lb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.user_task_view_pb.setText(QtGui.QApplication.translate("guerillamgmt_mwin", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.pages_tabw.setTabText(self.pages_tabw.indexOf(self.user_widget), QtGui.QApplication.translate("guerillamgmt_mwin", "User", None, QtGui.QApplication.UnicodeUTF8))

