# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dz016.CA\Documents\Jukebox\jukebox\addons\coreplugins\genesis\genesis.ui'
#
# Created: Mon Jun 23 20:20:47 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_genesis_mwin(object):
    def setupUi(self, genesis_mwin):
        genesis_mwin.setObjectName("genesis_mwin")
        genesis_mwin.resize(1009, 765)
        self.central_widget = QtGui.QWidget(genesis_mwin)
        self.central_widget.setObjectName("central_widget")
        self.central_vbox = QtGui.QVBoxLayout(self.central_widget)
        self.central_vbox.setObjectName("central_vbox")
        self.prj_banner_lb = QtGui.QLabel(self.central_widget)
        self.prj_banner_lb.setMinimumSize(QtCore.QSize(350, 100))
        self.prj_banner_lb.setText("")
        self.prj_banner_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.prj_banner_lb.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.prj_banner_lb.setObjectName("prj_banner_lb")
        self.central_vbox.addWidget(self.prj_banner_lb)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.work_rb = QtGui.QRadioButton(self.central_widget)
        self.work_rb.setChecked(True)
        self.work_rb.setObjectName("work_rb")
        self.horizontalLayout.addWidget(self.work_rb)
        self.release_rb = QtGui.QRadioButton(self.central_widget)
        self.release_rb.setObjectName("release_rb")
        self.horizontalLayout.addWidget(self.release_rb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.central_vbox.addLayout(self.horizontalLayout)
        self.selection_tabw = QtGui.QTabWidget(self.central_widget)
        self.selection_tabw.setObjectName("selection_tabw")
        self.asset_widget = QtGui.QWidget()
        self.asset_widget.setObjectName("asset_widget")
        self.asset_vbox = QtGui.QVBoxLayout(self.asset_widget)
        self.asset_vbox.setObjectName("asset_vbox")
        self.asset_splitter = QtGui.QSplitter(self.asset_widget)
        self.asset_splitter.setOrientation(QtCore.Qt.Vertical)
        self.asset_splitter.setObjectName("asset_splitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.asset_splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.asset_browser_vbox = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.asset_browser_vbox.setContentsMargins(0, 0, 0, 0)
        self.asset_browser_vbox.setObjectName("asset_browser_vbox")
        self.asset_info_gb = QtGui.QGroupBox(self.asset_splitter)
        self.asset_info_gb.setObjectName("asset_info_gb")
        self.asset_info_hbox = QtGui.QHBoxLayout(self.asset_info_gb)
        self.asset_info_hbox.setObjectName("asset_info_hbox")
        self.asset_info_grid = QtGui.QGridLayout()
        self.asset_info_grid.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.asset_info_grid.setObjectName("asset_info_grid")
        self.asset_thumb_lb = QtGui.QLabel(self.asset_info_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_thumb_lb.sizePolicy().hasHeightForWidth())
        self.asset_thumb_lb.setSizePolicy(sizePolicy)
        self.asset_thumb_lb.setMinimumSize(QtCore.QSize(160, 90))
        self.asset_thumb_lb.setFrameShape(QtGui.QFrame.Box)
        self.asset_thumb_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.asset_thumb_lb.setObjectName("asset_thumb_lb")
        self.asset_info_grid.addWidget(self.asset_thumb_lb, 0, 0, 4, 2)
        self.asset_created_by_le = QtGui.QLineEdit(self.asset_info_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_created_by_le.sizePolicy().hasHeightForWidth())
        self.asset_created_by_le.setSizePolicy(sizePolicy)
        self.asset_created_by_le.setReadOnly(True)
        self.asset_created_by_le.setObjectName("asset_created_by_le")
        self.asset_info_grid.addWidget(self.asset_created_by_le, 0, 3, 1, 1)
        self.asset_created_lb = QtGui.QLabel(self.asset_info_gb)
        self.asset_created_lb.setObjectName("asset_created_lb")
        self.asset_info_grid.addWidget(self.asset_created_lb, 1, 2, 1, 1)
        self.asset_created_dte = QtGui.QDateTimeEdit(self.asset_info_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_created_dte.sizePolicy().hasHeightForWidth())
        self.asset_created_dte.setSizePolicy(sizePolicy)
        self.asset_created_dte.setReadOnly(True)
        self.asset_created_dte.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.asset_created_dte.setObjectName("asset_created_dte")
        self.asset_info_grid.addWidget(self.asset_created_dte, 1, 3, 1, 1)
        self.asset_updated_lb = QtGui.QLabel(self.asset_info_gb)
        self.asset_updated_lb.setObjectName("asset_updated_lb")
        self.asset_info_grid.addWidget(self.asset_updated_lb, 2, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.asset_info_grid.addItem(spacerItem1, 5, 3, 1, 1)
        self.asset_created_by_lb = QtGui.QLabel(self.asset_info_gb)
        self.asset_created_by_lb.setObjectName("asset_created_by_lb")
        self.asset_info_grid.addWidget(self.asset_created_by_lb, 0, 2, 1, 1)
        self.asset_updated_dte = QtGui.QDateTimeEdit(self.asset_info_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_updated_dte.sizePolicy().hasHeightForWidth())
        self.asset_updated_dte.setSizePolicy(sizePolicy)
        self.asset_updated_dte.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.asset_updated_dte.setObjectName("asset_updated_dte")
        self.asset_info_grid.addWidget(self.asset_updated_dte, 2, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.asset_info_grid.addItem(spacerItem2, 3, 2, 1, 1)
        self.asset_open_path_tb = QtGui.QToolButton(self.asset_info_gb)
        self.asset_open_path_tb.setText("")
        self.asset_open_path_tb.setObjectName("asset_open_path_tb")
        self.asset_info_grid.addWidget(self.asset_open_path_tb, 4, 0, 1, 1)
        self.asset_path_le = QtGui.QLineEdit(self.asset_info_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.asset_path_le.sizePolicy().hasHeightForWidth())
        self.asset_path_le.setSizePolicy(sizePolicy)
        self.asset_path_le.setReadOnly(True)
        self.asset_path_le.setObjectName("asset_path_le")
        self.asset_info_grid.addWidget(self.asset_path_le, 4, 1, 1, 3)
        self.asset_info_hbox.addLayout(self.asset_info_grid)
        self.asset_vbox.addWidget(self.asset_splitter)
        self.asset_open_pb = QtGui.QPushButton(self.asset_widget)
        self.asset_open_pb.setMinimumSize(QtCore.QSize(200, 32))
        self.asset_open_pb.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.asset_open_pb.setFont(font)
        self.asset_open_pb.setObjectName("asset_open_pb")
        self.asset_vbox.addWidget(self.asset_open_pb)
        self.asset_new_hbox = QtGui.QHBoxLayout()
        self.asset_new_hbox.setObjectName("asset_new_hbox")
        self.asset_save_pb = QtGui.QPushButton(self.asset_widget)
        self.asset_save_pb.setMinimumSize(QtCore.QSize(200, 32))
        self.asset_save_pb.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.asset_save_pb.setFont(font)
        self.asset_save_pb.setObjectName("asset_save_pb")
        self.asset_new_hbox.addWidget(self.asset_save_pb)
        self.asset_descriptor_lb = QtGui.QLabel(self.asset_widget)
        self.asset_descriptor_lb.setObjectName("asset_descriptor_lb")
        self.asset_new_hbox.addWidget(self.asset_descriptor_lb)
        self.asset_descriptor_le = QtGui.QLineEdit(self.asset_widget)
        self.asset_descriptor_le.setObjectName("asset_descriptor_le")
        self.asset_new_hbox.addWidget(self.asset_descriptor_le)
        self.asset_vbox.addLayout(self.asset_new_hbox)
        self.selection_tabw.addTab(self.asset_widget, "")
        self.shot_widget = QtGui.QWidget()
        self.shot_widget.setObjectName("shot_widget")
        self.shot_vbox = QtGui.QVBoxLayout(self.shot_widget)
        self.shot_vbox.setObjectName("shot_vbox")
        self.splitter = QtGui.QSplitter(self.shot_widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.shot_browser_vbox = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.shot_browser_vbox.setContentsMargins(0, 0, 0, 0)
        self.shot_browser_vbox.setObjectName("shot_browser_vbox")
        self.shot_info_gb = QtGui.QGroupBox(self.splitter)
        self.shot_info_gb.setObjectName("shot_info_gb")
        self.shot_info_hbox = QtGui.QHBoxLayout(self.shot_info_gb)
        self.shot_info_hbox.setObjectName("shot_info_hbox")
        self.shot_info_grid = QtGui.QGridLayout()
        self.shot_info_grid.setObjectName("shot_info_grid")
        spacerItem3 = QtGui.QSpacerItem(20, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.shot_info_grid.addItem(spacerItem3, 3, 2, 1, 1)
        self.shot_thumb_lb = QtGui.QLabel(self.shot_info_gb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shot_thumb_lb.sizePolicy().hasHeightForWidth())
        self.shot_thumb_lb.setSizePolicy(sizePolicy)
        self.shot_thumb_lb.setMinimumSize(QtCore.QSize(160, 90))
        self.shot_thumb_lb.setFrameShape(QtGui.QFrame.Box)
        self.shot_thumb_lb.setAlignment(QtCore.Qt.AlignCenter)
        self.shot_thumb_lb.setObjectName("shot_thumb_lb")
        self.shot_info_grid.addWidget(self.shot_thumb_lb, 0, 0, 4, 2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.shot_info_grid.addItem(spacerItem4, 5, 3, 1, 1)
        self.shot_path_le = QtGui.QLineEdit(self.shot_info_gb)
        self.shot_path_le.setReadOnly(True)
        self.shot_path_le.setObjectName("shot_path_le")
        self.shot_info_grid.addWidget(self.shot_path_le, 4, 1, 1, 3)
        self.shot_updated_lb = QtGui.QLabel(self.shot_info_gb)
        self.shot_updated_lb.setObjectName("shot_updated_lb")
        self.shot_info_grid.addWidget(self.shot_updated_lb, 2, 2, 1, 1)
        self.shot_created_by_lb = QtGui.QLabel(self.shot_info_gb)
        self.shot_created_by_lb.setObjectName("shot_created_by_lb")
        self.shot_info_grid.addWidget(self.shot_created_by_lb, 0, 2, 1, 1)
        self.shot_created_by_le = QtGui.QLineEdit(self.shot_info_gb)
        self.shot_created_by_le.setObjectName("shot_created_by_le")
        self.shot_info_grid.addWidget(self.shot_created_by_le, 0, 3, 1, 1)
        self.shot_created_lb = QtGui.QLabel(self.shot_info_gb)
        self.shot_created_lb.setObjectName("shot_created_lb")
        self.shot_info_grid.addWidget(self.shot_created_lb, 1, 2, 1, 1)
        self.shot_created_dte = QtGui.QDateTimeEdit(self.shot_info_gb)
        self.shot_created_dte.setReadOnly(True)
        self.shot_created_dte.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.shot_created_dte.setObjectName("shot_created_dte")
        self.shot_info_grid.addWidget(self.shot_created_dte, 1, 3, 1, 1)
        self.shot_updated_dte = QtGui.QDateTimeEdit(self.shot_info_gb)
        self.shot_updated_dte.setReadOnly(True)
        self.shot_updated_dte.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.shot_updated_dte.setObjectName("shot_updated_dte")
        self.shot_info_grid.addWidget(self.shot_updated_dte, 2, 3, 1, 1)
        self.shot_open_path_tb = QtGui.QToolButton(self.shot_info_gb)
        self.shot_open_path_tb.setText("")
        self.shot_open_path_tb.setObjectName("shot_open_path_tb")
        self.shot_info_grid.addWidget(self.shot_open_path_tb, 4, 0, 1, 1)
        self.shot_info_hbox.addLayout(self.shot_info_grid)
        self.shot_vbox.addWidget(self.splitter)
        self.shot_open_pb = QtGui.QPushButton(self.shot_widget)
        self.shot_open_pb.setMinimumSize(QtCore.QSize(200, 32))
        self.shot_open_pb.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.shot_open_pb.setFont(font)
        self.shot_open_pb.setObjectName("shot_open_pb")
        self.shot_vbox.addWidget(self.shot_open_pb)
        self.shot_new_hbox = QtGui.QHBoxLayout()
        self.shot_new_hbox.setObjectName("shot_new_hbox")
        self.shot_save_pb = QtGui.QPushButton(self.shot_widget)
        self.shot_save_pb.setMinimumSize(QtCore.QSize(200, 32))
        self.shot_save_pb.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.shot_save_pb.setFont(font)
        self.shot_save_pb.setObjectName("shot_save_pb")
        self.shot_new_hbox.addWidget(self.shot_save_pb)
        self.shot_descriptor_lb = QtGui.QLabel(self.shot_widget)
        self.shot_descriptor_lb.setObjectName("shot_descriptor_lb")
        self.shot_new_hbox.addWidget(self.shot_descriptor_lb)
        self.shot_descriptor_le = QtGui.QLineEdit(self.shot_widget)
        self.shot_descriptor_le.setObjectName("shot_descriptor_le")
        self.shot_new_hbox.addWidget(self.shot_descriptor_le)
        self.shot_vbox.addLayout(self.shot_new_hbox)
        self.selection_tabw.addTab(self.shot_widget, "")
        self.central_vbox.addWidget(self.selection_tabw)
        genesis_mwin.setCentralWidget(self.central_widget)
        self.statusbar = QtGui.QStatusBar(genesis_mwin)
        self.statusbar.setObjectName("statusbar")
        genesis_mwin.setStatusBar(self.statusbar)

        self.retranslateUi(genesis_mwin)
        self.selection_tabw.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(genesis_mwin)

    def retranslateUi(self, genesis_mwin):
        genesis_mwin.setWindowTitle(QtGui.QApplication.translate("genesis_mwin", "Genesis", None, QtGui.QApplication.UnicodeUTF8))
        self.work_rb.setText(QtGui.QApplication.translate("genesis_mwin", "work", None, QtGui.QApplication.UnicodeUTF8))
        self.release_rb.setText(QtGui.QApplication.translate("genesis_mwin", "release", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_info_gb.setTitle(QtGui.QApplication.translate("genesis_mwin", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_thumb_lb.setText(QtGui.QApplication.translate("genesis_mwin", "File Snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_created_lb.setText(QtGui.QApplication.translate("genesis_mwin", "Created:", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_updated_lb.setText(QtGui.QApplication.translate("genesis_mwin", "Updated:", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_created_by_lb.setText(QtGui.QApplication.translate("genesis_mwin", "Created by:", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_open_pb.setText(QtGui.QApplication.translate("genesis_mwin", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_save_pb.setText(QtGui.QApplication.translate("genesis_mwin", "Save/New", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_descriptor_lb.setText(QtGui.QApplication.translate("genesis_mwin", "Descriptor:", None, QtGui.QApplication.UnicodeUTF8))
        self.selection_tabw.setTabText(self.selection_tabw.indexOf(self.asset_widget), QtGui.QApplication.translate("genesis_mwin", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_info_gb.setTitle(QtGui.QApplication.translate("genesis_mwin", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_thumb_lb.setText(QtGui.QApplication.translate("genesis_mwin", "File Snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_updated_lb.setText(QtGui.QApplication.translate("genesis_mwin", "Updated:", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_created_by_lb.setText(QtGui.QApplication.translate("genesis_mwin", "Created by:", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_created_lb.setText(QtGui.QApplication.translate("genesis_mwin", "Created:", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_open_pb.setText(QtGui.QApplication.translate("genesis_mwin", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_save_pb.setText(QtGui.QApplication.translate("genesis_mwin", "Save/New", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_descriptor_lb.setText(QtGui.QApplication.translate("genesis_mwin", "Descriptor:", None, QtGui.QApplication.UnicodeUTF8))
        self.selection_tabw.setTabText(self.selection_tabw.indexOf(self.shot_widget), QtGui.QApplication.translate("genesis_mwin", "Shots", None, QtGui.QApplication.UnicodeUTF8))

